server:
  port: 8761

spring:
    application:
        name: eureka-server

eureka:
  instance:
    client:
      registerWithEureka: false
      fetchRegistry: false
      service-url:
        defauntZone: http://${eureka.instance.hostname}:${server.port}/eureka/

    hostname: localhost
